### ISSUE TITLE
medium article / question

### ISSUE THREAD

**Issue by roscopecoltran** [cxww107/asyncwork#1]
Hi guys,

Hope you are all well !

I was wondering how I could be triggering some events cascading and async tasks based on your article. Let me just quickly share an overview of my problem/project. :-)

**Use case:**

1. **Pitch:** I want to manage my starred repository, and actually I use [limo](https://github.com/hoop33/limo/blob/master/cmd/update.go), written in go also.
2. **Goal:** Extend the update process, by fetching some additional informations from my [starred](https://github.com/google/go-github/blob/master/github/activity_star.go#L66-L97) repository like [languages](https://github.com/google/go-github/blob/master/github/repos.go#L455-L469), the [readme](https://github.com/google/go-github/blob/master/github/repos_contents.go#L88-L107) content and the [file tree ](https://github.com/google/go-github/blob/master/github/git_trees.go#L40-L61)for the latest SHA.
3. **Workflow**: 
    - Create a parent channel, with a concurrency of 20, like actually [in the update.go file from limo](https://github.com/hoop33/limo/blob/master/cmd/update.go#L43-L79), to fetch the list of my starred repo (per page: 100)
        - Fetch the readme (if exists), the git tree and the detected languages for each of them 
        - Maybe 2 or 3 conditional requests per repository (eg. they have a wiki or more documents like additional markdowns)
4. **Bottleneck**:
        - How to configure this task of parallel and waterfall requests ? 
            - How can I control that some missing readme, or some api requests errors won't break the integrity of my task-flow ?
        - What would describe the best my problem ? 
            - Is it a much more a flow based programming (fbp) problem ?
            - Can I just use async commands by defining the flow within a simple yaml config ? 

In fact, I would like to find or understand the easier approach to aggregate these data and not having un-optimized use of my goroutines.  

Thanks again for your article !

Cheers,
Richard

**Comment by nbys** [comment]
@roscopecoltran Hi Richard,

well I don’t think that you necessarily need to use this project to achieve your goal. But you could use it like that: https://gist.github.com/cxww107/8be29c785d36c4b6b5811f8dac5a052d (this snippet is a copy of function GetStars from github.go of limo project. I inserted lines at 29-60)

Task. You have a list with starred repos. For each repo you need extract some information. Then I would say the task is: for a given repo to send some requests for meta data, readme, languages etc. For example you have 2000 starred repos. In other words you have 2000 tasks that could run parallel. 

Errors. You can decide by yourself when error is critical enough to stop processing. But as I see in current implementation of limo they simply send the error through result channel to the client. 

Un-optimized goroutines. It is possible that one repo has three source files and other one has a thousand. Then processing of the second repo logically would last longer. But still I think that’s ok. You have the granularity, all data related to one given repo will be processing in only one separated goroutine. You can notice that I reused context: that means if you kill process at upper level it would stop execution of tasks here as well. So no dead goroutines will hang around.

I hope this info can help you.

Regards,
Nikolay
